apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprod-nginx
  labels:
    app: preprod-nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprod-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: preprod-nginx
    spec:
      containers:
        - name: preprod-nginx
          image: adityakumar10mm/nginx-grafana:v1
          ports:
            - containerPort: 80
          resources:   # Add the resource limits and requests here
            limits:
              cpu: ".5"   # The maximum CPU the container can use
              memory: "1Gi"   # The maximum memory the container can use
            requests:
              cpu: ".5"   # The minimum CPU required by the container
              memory: "1Gi"   # The minimum memory required by the container
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 4001
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   failureThreshold: 3
          #   timeoutSeconds: 60