apiVersion: v1
kind: Service
metadata:
  name: preprod-nginx-svc
  namespace: dev
spec:
  selector:
    app: preprod-nginx
  ports:
    - protocol: "TCP"
      targetPort: 80
      port: 80
  type: ClusterIP