prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      existingClaim: prometheus-pvc

  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          enabled: false
        existingClaim: alertmanager-pvc

loki:
  enabled: true
  persistence:
    enabled: true
    existingClaim: loki-pvc

promtail:
  enabled: true

grafana:
  enabled: true
  adminPassword: "admin"
  persistence:
    enabled: false

  grafana.ini:
    server:
      root_url: http://3.239.184.62/mon/
      serve_from_sub_path: true